### NumPy Constants

In [1]:
import numpy as np
import scipy

In [2]:
# NumPy uses the IEEE Standard for Binary Floating-Point 
# for Arithmetic (IEEE 754). 
# This means that Not a Number is not equivalent to infinity. 
# Also that positive infinity is not equivalent to negative infinity. 
# But infinity is equivalent to positive infinity.

In [3]:
# NaN and NAN are equivalent definitions of nan. 
# Please use nan instead of NAN.
print(np.nan)
print(type(np.nan))

nan
<class 'float'>


In [4]:
# IEEE 754 floating point representation of (positive) infinity.
# Use inf because Inf, Infinity, PINF and infty are aliases for inf.
np.Inf

inf

In [5]:
# IEEE 754 floating point representation of negative infinity.
# Single name - NINF, others like nanf, Nanf are invalid
np.NINF 

-inf

In [6]:
# Negative Infinite
np.NINF

-inf

In [7]:
np.log(0)

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


-inf

In [8]:
# IEEE 754 floating point representation of negative zero.
np.NZERO # USe same name

-0.0

In [9]:
np.PZERO # positive zero

0.0

In [11]:
# Use inf because Inf, Infinity, PINF and infty are aliases for inf
np.PINF

inf

In [12]:
# PI
np.pi

3.141592653589793

In [13]:
np.array([1]) / 0.

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([ inf])

In [14]:
# Euler’s constant, base of natural logarithms, Napier’s constant.
np.e

2.718281828459045

In [15]:
# Methods on constants
np.isfinite([np.NZERO])

array([ True], dtype=bool)

In [16]:
np.isnan([np.NZERO])

array([False], dtype=bool)

In [17]:
np.isinf([np.NZERO])

array([False], dtype=bool)