### Creating NumPy Array using intrinsic methods
#### List of Intrinsic methods - empty, zeros, ones, full, eye...

#### 1. numpy.empty
numpy.empty(shape, dtype=float, order='C')

Return a new array of given shape and type, without initializing entries.

#### Parameters:	
- **shape :** int or tuple of int
  Shape of the empty array, e.g., (2, 3) or 2.

- **dtype :** data-type, optional
  Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.

- **order :** {‘C’, ‘F’}, optional, default: ‘C’
  Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

In [1]:
import numpy as np

In [2]:
# Create an array of 4 elements 
# Default dtype is float64
# initialized with garbage values

np.empty(4) 

array([  1.62084686e-312,   1.62032737e-312,   1.01270461e-313,
         1.61271680e-312])

In [3]:
# Create 2-D array of size 2x2

np.empty([2, 2]) # Default dtype is float64

# np.empty((2,2))  # Correct? Can I keep the dimensions in tuple instead of list?

array([[ 0.,  0.],
       [ 0.,  0.]])

In [4]:
# Create a 2x2 integer array with C type storage
np.empty([2, 2], dtype=int, order='C')

array([[1629314384,         76],
       [1629314384,         76]])

In [5]:
# Can I add elements to an empty array?
A = np.empty(4, dtype=int)
A[0] = 0
A[1] = 1
A[2] = 2
A[3] = 3
print(A)

[0 1 2 3]


#### 2. numpy.zeros(shape, dtype=float, order='C')

- Return a new array of given shape and type, filled with zeros.

In [6]:
arr1 = np.zeros(4) # Default float64
arr1

array([ 0.,  0.,  0.,  0.])

In [7]:
arr1 = np.zeros((4,4), dtype=bool) # Default False
arr1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [8]:
arr1 = np.zeros((4,4), dtype=str) # Default emty string
arr1

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], 
      dtype='<U1')

In [9]:
#arr1 = np.zeros((4,4), dtype=void) # Cant use void here, because it has to initialize with some thing
#arr1

#### 3. np.ones --> numpy.ones(shape, dtype=None, order='C')[source]
- Return a new array of given shape and type, filled with ones.

In [10]:
arr1 = np.ones() # Shape is mandatory

TypeError: ones() missing 1 required positional argument: 'shape'

In [12]:
# If you mention dtype as None then it takes it as float64
np.ones(4, dtype=None, order='C') 

array([ 1.,  1.,  1.,  1.])

In [13]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [14]:
np.ones((4,4), dtype=str) # Fills with '1' character

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], 
      dtype='<U1')

In [15]:
arr1 = np.ones(4, dtype=bool) # Fills with True
print(arr1)

[ True  True  True  True]


#### 4. full - It has one extra argument "fill_value"
Signature: 

numpy.full(shape, fill_value, dtype=None, order='C')[source]

- Return a new array of given shape and type, filled with fill_value.
- fill_value is any scalar

In [16]:
arr1 = np.full(4, 5.6) # Fill the array with 5.6
arr1

array([ 5.6,  5.6,  5.6,  5.6])

In [17]:
arr1 = np.full(4, 5.6, dtype=int) # truncates float to int
arr1

array([5, 5, 5, 5])

In [18]:
# truncates float to int, then convert to char
arr1 = np.full(4, 5.6, dtype=str) 
print(arr1)

['5' '5' '5' '5']


In [19]:
# ??? It can fill only with a scalar, what it will do?
arr1 = np.full(4, "ram", dtype=str)
print(arr1)

['r' 'r' 'r' 'r']


In [20]:
np.full(4, np.inf)

array([ inf,  inf,  inf,  inf])

#### 5. eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

#### Parameters:	

N : int
Number of rows in the output.

M : int, optional
Number of columns in the output. If None, defaults to N.

k : int, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

dtype : data-type, optional
Data-type of the returned array.

order : {‘C’, ‘F’}, optional
Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.

In [21]:
# Creates a diagonal matrix and intializes with 1.0, a float64
np.eye(3, 3) 

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [22]:
np.eye(3) # If only nrows (M) is mentioned then it considers it as MxM matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [23]:
np.eye(3, 4) 

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [24]:
np.eye(6, 6, k=2, dtype=int) # Upper 2nd diagonal will be intialized with 1s

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [25]:
np.eye(6, 6, dtype=str) # Strings??? Diagonal is initialize with Little endian unicode '1's

array([['1', '', '', '', '', ''],
       ['', '1', '', '', '', ''],
       ['', '', '1', '', '', ''],
       ['', '', '', '1', '', ''],
       ['', '', '', '', '1', ''],
       ['', '', '', '', '', '1']], 
      dtype='<U1')

### 6. np.identity

Signature: np.identity(n, dtype=None)

Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

#### Parameters

n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.

#### Returns

out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

In [26]:
np.identity(3) # Pure identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [27]:
np.identity(3, dtype=str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], 
      dtype='<U1')

### 7. empty_like

Docstring:

empty_like(a, dtype=None, order='K', subok=True)

Return a new array with the same shape and type as a given array.

#### Parameters
a : array_like
    The shape and data-type of `a` define these same attributes of the
    returned array.

dtype : data-type, optional
    Overrides the data type of the result.

    .. versionadded:: 1.6.0

order : {'C', 'F', 'A', or 'K'}, optional
    Overrides the memory layout of the result. 'C' means C-order,
    'F' means F-order, 'A' means 'F' if ``a`` is Fortran contiguous,
    'C' otherwise. 'K' means match the layout of ``a`` as closely
    as possible.

    .. versionadded:: 1.6.0

subok : bool, optional.
    If True, then the newly created array will use the sub-class
    type of 'a', otherwise it will be a base-class array. Defaults
    to True.

#### Returns

out : ndarray
    Array of uninitialized (arbitrary) data with the same
    shape and type as `a`.


In [28]:
a1 = np.empty(4, dtype=int)

# Create an empty array like 'a1'
a2 = np.empty_like(a1) 

print(a1)
print(a2)

a1 is a2

[1 1 1 1]
[1 1 1 1]


False

In [29]:
a1 = np.empty(4)

# Change the data type from the original - flaot64 to int
a2 = np.empty_like(a1, dtype = int) 
a2

array([1, 1, 1, 1])

In [30]:
a1 = np.empty(4)
a2 = np.empty_like(a1, subok=True) # Both belong to the same class "ndarray"
print(type(a1))
print(type(a2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [31]:
# Matrix is a subclass of ndarray, 

# so it "converts ndarray object to matrix sub class object"

a1 = np.array(np.mat((2,2)), subok=True) 

print(type(a1))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [32]:
a1 = np.array(np.mat((2,2)), subok=False)
print(type(a1))

<class 'numpy.ndarray'>


### 8. np.diag  - Create a diagonal matrix

In [33]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### How to protect the data in a NumPy Array?
### Can we make it immutable?

In [34]:
import numpy as np
x = np.ones(10)
print(x)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [35]:
x.flags.writeable = False
x[0] = 1

ValueError: assignment destination is read-only

In [8]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False