## Create ndarray using existing objects

In general, numerical data arranged in an array-like structure in Python (Lists, Tuples etc) can be converted to arrays through the use of the array() function.

### numpy.array

### Syntax

numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

### Parameters:	

- object : array_like
  An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence.

- dtype : data-type, optional
- The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence. This argument can only be used to ‘upcast’ the array. For downcasting, use the .astype(t) method.

- copy : bool, optional
If true (default), then the object is copied. Otherwise, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.).

- order : {‘K’, ‘A’, ‘C’, ‘F’}, optional
Specify the memory layout of the array. If object is not an array, the newly created array will be in C order (row major) unless ‘F’ is specified, in which case it will be in Fortran order (column major). If object is an array the following holds.

        order	        copy=False	         copy=True
    
        ‘K’	             unchanged	         F & C order preserved, otherwise most similar order
     
        ‘A’	             unchanged	         F order if input is F and not C, otherwise C order
    
        ‘C’	             C order	         C order
     
        ‘F’	             F order	         F order

When copy=False and a copy is made for other reasons, the result is the same as if copy=True, with some exceptions for A, see the Notes section. The default order is ‘K’.

- subok : bool, optional
If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array (default).

- ndmin : int, optional
Specifies the minimum number of dimensions that the resulting array should have. Ones will be pre-pended to the shape as needed to meet this requirement.

- Returns:	
out : ndarray
An array object satisfying the specified requirements.

In [1]:
import numpy as np

In [2]:
# Create an array from a list
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# Create an array from a tuple
np.array((1,2,3))

array([1, 2, 3])

In [5]:
A = np.array("ram")
print(type(A))
A
A[0]

<class 'numpy.ndarray'>


IndexError: too many indices for array

In [6]:
# Is it correct?
A = np.array({1:'a', 2:'b'})
print(type(A))
A.shape
A[0]

<class 'numpy.ndarray'>


IndexError: too many indices for array

In [7]:
# Upcasting
np.array([1, 2, 3.0]) # Convert ints to float64

array([ 1.,  2.,  3.])

In [8]:
# More dimensions
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [9]:
# Create a complex array
np.array([1, 2, 3], dtype=complex)

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [10]:
# complex matrix
np.array([(1,2), (3,4)], dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [11]:
# Create a complex array
d = np.array([1+2j, 3+4j, 5+6*1j])

print(d)

print(d.real)
print(d.imag)

[ 1.+2.j  3.+4.j  5.+6.j]
[ 1.  3.  5.]
[ 2.  4.  6.]


In [12]:
# Data type consisting of more than one type
# In a row, first elements is int and 2nd element is float

x = np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<f4')])
print(x)

[(1, 2.0) (3, 4.0)]


In [13]:
# Creating array from subcalls
# Array from matrix
m1 = np.mat('1,2 ; 3,4')
type(m1)

numpy.matrixlib.defmatrix.matrix

In [14]:
m2 = np.array(np.mat('1,2 ; 3,4'))
type(m2)

numpy.ndarray

In [15]:
m2 = np.array(np.mat('1,2 ; 3,4'), subok=True)
type(m2)

numpy.matrixlib.defmatrix.matrix

In [16]:
# copy = True - Creates another copy from the object
L = [1,2,3,4]
A = np.array(L, copy = True)

print(id(L), id(A)) #Same IDS?

1053663125640 1053655680064


In [17]:
# copy = False

A1 = np.array([1,2,3,4])
A2 = np.array(A1, copy = False)

print(id(A1), id(A2)) # Same IDs?

1053655679984 1053655679984


In [18]:
# copy = True

A1 = np.array([1,2,3,4])
A2 = np.array(A1, copy = True)

print(id(A1), id(A2))  # Same IDs?

1053655681744 1053655680544


In [20]:
# Minimum number of dimensions
import numpy as np 
a = np.array([1, 2, 3, 4, 5], ndmin = 3) # A 1x1X5 matrix
print(a)
print(a.shape)

[[[1 2 3 4 5]]]
(1, 1, 5)


### 2. np.asarray

#### Syntax:

numpy.asarray(a, dtype=None, order=None)

#### Purpose:
Convert the input to an array.

#### Parameters:

- a : array_like
Input data, in any form that can be converted to an array. This includes lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.

- dtype : data-type, optional
By default, the data-type is inferred from the input data.

- order : {‘C’, ‘F’}, optional
Whether to use row-major (C-style) or column-major (Fortran-style) memory representation. Defaults to ‘C’.

#### Returns:	
out : ndarray
Array interpretation of a. No copy is performed if the input is already an ndarray with matching dtype and order. If a is a subclass of ndarray, a base class ndarray is returned.

In [21]:
>>> L = [1, 2]
>>> L = np.asarray(a)
print(type(L))

<class 'numpy.ndarray'>


In [22]:
# Existing arrays are not copied
>>> a = np.array([1, 2])
>>> np.asarray(a) is a

True

### 3. np.asmatrix

#### Prototype
numpy.asmatrix(data, dtype=None)

#### Purpose
Interpret the input as a matrix.

Unlike matrix, asmatrix does not make a copy if the input is already a matrix or an ndarray. 

Equivalent to matrix(data, copy=False).

#### Parameters:	
- data : array_like
- Input data.

- dtype : data-type
  Data-type of the output matrix.

#### Returns:	
mat : matrix
data interpreted as a matrix.

In [23]:
>>> x = np.array([[1, 2], [3, 4]])
print(x)
print(type(x))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [24]:
m = np.asmatrix(x)
print(m)
print(type(m))

[[1 2]
 [3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [25]:
x[0]

array([1, 2])

In [26]:
m[0]

matrix([[1, 2]])

### 4. np.copy
#### Syntax
np.copy(a, order='C')

Return an array copy of the given object.

Equivalent to - np.array(a, copy=True)  

In [27]:
x = np.array(["abc", "def"])
y = np.copy(x)
x is y

False

In [28]:
z = x
x is z

True

### 5. arange

This function returns an ndarray object containing evenly spaced values within a given range. 

The format of the function is as follows −

**numpy.arange(start, stop, step, dtype)**

In [29]:
x = np.arange(5, dtype = float)
x

array([ 0.,  1.,  2.,  3.,  4.])

In [30]:
x = np.arange(0, 100, 10, dtype = float) # Excluding 100
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

### linspace

This function is similar to arange() function. 

In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

**numpy.linspace(start, stop, num, endpoint, retstep, dtype)**

#### Arguments

- start

  The starting value of the sequence
  
- stop
  
   The end value of the sequence, included in the sequence if endpoint set to true
   
- num

   The number of evenly spaced samples to be generated. Default is 50.
   
- endpoint

   True by default, hence **the stop value is included in the sequence**. If false, it is not included.
   
- retstep

   If true, returns samples and step between the consecutive numbers
   
- dtype  
   


In [31]:
x = np.linspace(10,20,5) # last number included
print(x)

[ 10.   12.5  15.   17.5  20. ]


In [33]:
x = np.linspace(10,20, 5, endpoint = False)  # last number 20.0 is excluded
print(x)

[ 10.  12.  14.  16.  18.]


In [34]:
x = np.linspace(1,2,5, retstep = True)  # Step 0.25 is returned as part of array
print(x)

(array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ]), 0.25)


### logspace

This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. 
Start and stop endpoints of the scale are indices of the base, usually 10.

**numpy.logspace(start, stop, num, endpoint, base, dtype)**

In [35]:
a = np.logspace(1.0, 2.0, num = 10) 
print(a) # default is bse10

[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [36]:
a = np.logspace(1,10,num = 10, base = 2)  # base 2, endpoint is True, returns 10 values
print(a)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]
