## Array Atributes

** The information of an array will be obtained using it's attributes**

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [3]:
# Invert the shape (Not transpose)
a = np.array([[1,2,3],[4,5,6]]) # Original shape 2x3 or (2,3s)
a.shape = (3,2) # Change it to 3x2
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# Reshape using a function - reshape
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
# get the number of dimensions
a = np.array([[1,2], [3,4]])
a.ndim

2

In [6]:
# get the number of dimensions
a = np.array([[[1,2], [3,4]]])
print(a.shape)
a.ndim

(1, 2, 2)


3

In [7]:
# Create a 1D Array
a = np.arange(24) 
print(a.ndim)  

# now reshape it  to 2x4x3 - 2rows, 4cols, 3depth
b = a.reshape(2,4,3)
b

1


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [8]:
# numpy.itemsize
# This array attribute returns the length of each element 
# of array in bytes.

x = np.array([1,2,3,4,5], dtype = np.int8) 
x.itemsize

1

In [9]:
x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x.itemsize)

4


In [10]:
x = np.array([256, 342, 554], dtype = np.int8) 
x.itemsize

1

In [11]:
#x = np.array(["abc", "deg", "ddd"], dtype = str) 
#x.itemsize

In [12]:
x = np.array([1,2,3,4,5]) 
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [13]:
# Get Python buffer object pointing to the start of the array’s data.
import numpy as np
x = np.array([256, 342, 554], dtype = np.int8) 
x.data # 

In [14]:
# Number of elemnts
x.size

3

In [15]:
x.nbytes

3

## Other Atributes

In [17]:
A = np.array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Transpose
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
A.flat # A 1-D iterator over the array.
for i in A.flat:
    print(i)

1
2
3
4
5
6
