## Array indexing

In [1]:
import numpy as np

In [5]:
x = np.array(['ram', 'john', 'panda'])
x[0]
#x[0][0]

'ram'

In [6]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7] # Excludes 7

array([1, 2, 3, 4, 5, 6])

In [7]:
x[1:10:2] # Print all odd numbers, i.e. with step 2

array([1, 3, 5, 7, 9])

In [8]:
# Negative i and j are interpreted as n + i and n + j 
# where n is the number of elements in the corresponding dimension. 

# Negative k makes stepping go towards smaller indices.

x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x[-2:10])

[8 9]


In [9]:
# Multi dimensional arrays
x = np.array([[[1],[2],[3]], [[4],[5],[6]]]) # 2x3x1
print(x.shape)
x

(2, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [10]:
x[1:2]

array([[[4],
        [5],
        [6]]])

### Advanced indexing

In [15]:
# Slicing can include "Ellipsis"

# to make a selection tuple of the same length 
# as the dimension of an array. 

# If ellipsis is used at the row position, 
# it will return an ndarray comprising of items in rows.

a = np.array([[1,2,3],[4,5,6],[5,6,7]]) 

In [16]:
a.shape

(3, 3)

In [17]:
# get the items in oth, 1st and 2nd columns

print(a[..., 0])
print(a[..., 1])
print(a[..., 2])

[1 4 5]
[2 5 6]
[3 6 7]


In [19]:
# Get all items in 0th row, 1st row, 2nd row
print(a[0,...]) # Get all the elements of the 0th diemnsion
print(a[1,...])
print(a[2,...])

[1 2 3]
[4 5 6]
[5 6 7]


In [20]:
# 2rows, 3 columns and 1 width
x = np.array([[[1],[2],[3]], [[4],[5],[6]]]) # 2x3x1

# Get all the elements of index 0 in the last dimension - 2x3
print(x[..., 0])

[[1 2 3]
 [4 5 6]]


In [21]:
# Get the 0th row - Allthe cols and width - 3x1
print(x[0,...])

[[1]
 [2]
 [3]]


In [22]:
# There may only be a single ellipsis present.
x[...,...]

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: VisibleDeprecationWarning: an index can only have a single Ellipsis (`...`); replace all but one with slices (`:`).
  from ipykernel import kernelapp as app


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [23]:
#  Get a specific element from each row - 

# Get 0th of oth row, 1st of 1st row, 0th of 2nd row

#  [ 1, 2 
#    3, 4
#    5, 6 ]
#
x = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2 array
print(x.shape)

# x[[r0, r1, r2], [c0, c1, c2]] --> x[r0, c0], x[r1, c1], x[r2,c2]
y = x[[0,1,2], [0,1,0]]  # x[0,0], x[1,1], x[2,0]
y

(3, 2)


array([1, 4, 5])

In [24]:
# Question: From a 4x3 array, all elements for which
# the column is one of [0, 2] 
# and the row is one of [0, 3] need to be selected  

# i.e. elements at (0,0), (0,2), (3,0), (3,2)
#
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
# Can we slice??? No.

# Solution1: Accessing individual elements
print(x[0,0], x[0,2], x[3,0], x[3,2])

# Solution 2: A loop - C type logic
for i in [0, 3]:  # row
    for j in [0, 2]:
        print(x[i,j], end=" ")
        
# Solution3: NumPy type solution - x[row indices, column indices] - rows - 0,3, cols - 0,2
print(x[ [[0,0], [3,3]], [[0,2], [0,2]] ])

0 2 9 11
0 2 9 11 [[ 0  2]
 [ 9 11]]


In [26]:
# Other example
x[1:2, 1:3]
#x[1:2, [1, 2]]

array([[4, 5]])

## Bollean Array indexing

In [27]:
# Bollean Array indexing
x = np.array([1., -1., -2., 3])
x[x < 0] += 20 # Add 20 to all the negative values
x

array([  1.,  19.,  18.,   3.])

In [28]:
# Return the sum of the array elements over the given axis.
x = np.array([[0, 1], [1, 1], [2, 2]])

print(x)

print()

print(x.sum(0)) # Axis 0 - col
print(x.sum(1)) # Axis 1 - row

[[0 1]
 [1 1]
 [2 2]]

[3 4]
[1 2 4]


In [29]:
# Example: From an array, select all rows which 
# sum up to less or equal two

x = np.array([[0, 1], [1, 1], [2, 2]])

rowsum = x.sum(1) # Get the sum of each row

x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

In [30]:
# Example
# Use boolean indexing to select all rows 
# adding up to an even number. 

# At the same time columns 0 and 2 should be 
# selected with an advanced integer index (ix_ method)

x = np.array([[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]])

# Get the rows with even sums
rows = (x.sum(1) % 2) == 0
print(rows)

[False  True False  True]


In [31]:
# Get the elements from cols - 0,2 and sum of row should be even
columns = [0, 2]
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

### np.flat  --> Flat iterator indexing - A 1-D iterator over the array.


In [32]:
x = np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
x.flat # flattened array

In [34]:
x.flat[0]

1

In [35]:
x.flat[5]

6

In [36]:
x.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [37]:
x.T.flat[3]

5

In [38]:
x.flat = 3  # all elements become 3
x

array([[3, 3, 3],
       [3, 3, 3]])

In [39]:
x.flat[[1,4,5,2]] = 0
x

array([[3, 0, 0],
       [3, 0, 0]])