## Universal Functions

### Why not loops?

In [1]:
# Method 1 - Loops
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    
    # Using loop
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

big_array = np.random.randint(1, 100, size=100000)
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 181 ms per loop


In [2]:
# Method - Numpy ufunc - / is wrapper over ufunc 'divide'
%timeit (1.0 / big_array)

The slowest run took 5.15 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 102 µs per loop


### Vectorized operations in NumPy are implemented via ufuncs, whose main purpose is to quickly execute repeated operations on values in NumPy arrays. Ufuncs are extremely flexible – before we saw an operation between a scalar and an array, but we can also operate between two arrays:

### And ufunc operations are not limited to one-dimensional arrays–they can also act on multi-dimensional arrays as well:

In [5]:
np.arange(5) / np.arange(1, 6) # [0, 1, 2, 3, 4] / [1, 2, 3, 4, 5] --> [0/1, 1/2, 2/3, 3/4, 4/5]

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [6]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

## Array Arithmetic

In [7]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [8]:
# There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In [9]:
print(-(0.5*x + 1) ** 2)

[-1.   -2.25 -4.   -6.25]


### Note: Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy; for example, 

### + operator is a wrapper for the "add" function:

In [10]:
# Both are same
np.add(x, 2)
x + 2

array([2, 3, 4, 5])

In [13]:
x = np.array([-2, -1, 0, 1, 2])
np.absolute(x)
# OR
np.abs(x)

array([2, 1, 0, 1, 2])

## Trignometric Functions
### NumPy provides a large number of useful ufuncs, and some of the most useful for the data scientist are the trigonometric functions. 

In [15]:
theta = np.linspace(0, np.pi, 3)
theta

array([ 0.        ,  1.57079633,  3.14159265])

In [16]:
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [ 0.          1.57079633  3.14159265]
sin(theta) =  [  0.00000000e+00   1.00000000e+00   1.22464680e-16]
cos(theta) =  [  1.00000000e+00   6.12323400e-17  -1.00000000e+00]
tan(theta) =  [  0.00000000e+00   1.63312394e+16  -1.22464680e-16]


In [17]:
# Inverse Trignometric
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [ 3.14159265  1.57079633  0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## Exponents and Logorithms

In [18]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [  2.71828183   7.3890561   20.08553692]
2^x   = [ 2.  4.  8.]
3^x   = [ 3  9 27]


In [19]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x)  = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]
