### Swap two rows of an array

In [2]:
import numpy as np

In [4]:
A = np.arange(25).reshape(5,5)
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [6]:
# Swap 1st and 3rd row
A[[1,3]] = A[[3,1]]
print(A)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 0  1  2  3  4]
 [20 21 22 23 24]]


In [8]:
# Note
print(A[[1,3]]) # Subarray of A
print(A[[3,1]])

[[15 16 17 18 19]
 [ 0  1  2  3  4]]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
